import { CurrencyPipe, DecimalPipe } from '@angular/common';
import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { LucideCalendarRange, LucideChartNoAxesCombined, LucideRefreshCw } from '@lucide/angular';
import { ApiClientService } from '../../../../core/http/api-client.service';
import { BarChartComponent } from '../../../../shared/charts/bar-chart/bar-chart.component';
import { DonutChartComponent } from '../../../../shared/charts/donut-chart/donut-chart.component';
interface RevenueReport{total:number;count:number;byMethod:{method:string;amount:number;count:number}[]}
interface Occupancy{date:string;totalRooms:number;occupiedRooms:number;occupancyRate:number}
@Component({selector:'app-reports-page',standalone:true,imports:[CurrencyPipe,DecimalPipe,FormsModule,LucideCalendarRange,LucideChartNoAxesCombined,LucideRefreshCw,BarChartComponent,DonutChartComponent],templateUrl:'./reports.page.html',styleUrl:'./reports.page.css',changeDetection:ChangeDetectionStrategy.OnPush})
export class ReportsPage {private readonly api=inject(ApiClientService);from=this.date(-30);to=this.date(0);readonly revenue=signal<RevenueReport|null>(null);readonly occupancy=signal<Occupancy[]>([]);readonly loading=signal(false);constructor(){this.load()}load(){this.loading.set(true);const days=Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-6+i);return this.dateObj(d)});this.api.get<RevenueReport>('reports/revenue',{from:this.from,to:this.to}).subscribe(r=>this.revenue.set(r));let pending=days.length;const rows:Occupancy[]=[];for(const d of days)this.api.get<Occupancy>('reports/occupancy',{date:d}).subscribe({next:r=>rows.push(r),complete:()=>{pending--;if(!pending){rows.sort((a,b)=>a.date.localeCompare(b.date));this.occupancy.set(rows);this.loading.set(false)}}})}labels(){return this.occupancy().map(x=>new Date(x.date+'T00:00:00').toLocaleString('en-US',{weekday:'short'}))}values(){return this.occupancy().map(x=>x.occupancyRate)}avgOccupancy(){const v=this.values();return v.length?v.reduce((sum,value)=>sum+value,0)/v.length:0}paymentSegments(){return (this.revenue()?.byMethod??[]).map(x=>({label:x.method,value:x.amount}))}private date(add:number){const d=new Date();d.setDate(d.getDate()+add);return this.dateObj(d)}private dateObj(d:Date){return d.toISOString().slice(0,10)}}
