import { ChangeDetectionStrategy, Component, inject, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { LucideCirclePlus, LucideCrown, LucideMail, LucidePencil, LucidePhone, LucideSearch, LucideUserRound } from '@lucide/angular';
import { ApiClientService } from '../../../../core/http/api-client.service';
import { normalizePaged, PagedResult } from '../../../../shared/models/paged-result.model';
import { ModalComponent } from '../../../../shared/ui/modal/modal.component';
import { PagerComponent } from '../../../../shared/ui/pager/pager.component';
import { ToastService } from '../../../../shared/ui/toast/toast.service';
interface Guest{id:string;firstName:string;lastName:string;fullName:string;phone?:string;email?:string;isVip:boolean}
@Component({selector:'app-guests-page',standalone:true,imports:[FormsModule,LucideCirclePlus,LucideCrown,LucideMail,LucidePencil,LucidePhone,LucideSearch,LucideUserRound,ModalComponent,PagerComponent],templateUrl:'./guests.page.html',styleUrl:'./guests.page.css',changeDetection:ChangeDetectionStrategy.OnPush})
export class GuestsPage implements OnInit {private readonly api=inject(ApiClientService);private readonly toast=inject(ToastService);readonly rows=signal<Guest[]>([]);readonly page=signal(1);readonly total=signal(0);readonly search=signal('');readonly modal=signal(false);readonly editId=signal<string|null>(null);firstName='';lastName='';phone='';email='';ngOnInit(){this.load()}load(){this.api.get<PagedResult<Guest>|Guest[]>('guests',{pageNumber:this.page(),pageSize:20,search:this.search()}).subscribe(v=>{const p=normalizePaged(v);this.rows.set(p.items);this.total.set(p.totalItems)})}setSearch(e:Event){this.search.set((e.target as HTMLInputElement).value);this.page.set(1);this.load()}changePage(p:number){this.page.set(p);this.load()}openCreate(){this.editId.set(null);this.firstName='';this.lastName='';this.phone='';this.email='';this.modal.set(true)}openEdit(x:Guest){this.editId.set(x.id);this.firstName=x.firstName;this.lastName=x.lastName;this.phone=x.phone??'';this.email=x.email??'';this.modal.set(true)}save(){const body={firstName:this.firstName,lastName:this.lastName,phone:this.phone||null,email:this.email||null};const id=this.editId();const req=id?this.api.put<Guest>(`guests/${id}`,body):this.api.post<Guest>('guests',body);req.subscribe(()=>{this.toast.success('Guest saved');this.modal.set(false);this.load()})}}
