import { ChangeDetectionStrategy, Component, inject, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { LucideCirclePlus, LucideDoorOpen, LucidePencil, LucideSearch, LucideTrash2 } from '@lucide/angular';
import { ApiClientService } from '../../../../core/http/api-client.service';
import { normalizePaged, PagedResult } from '../../../../shared/models/paged-result.model';
import { ModalComponent } from '../../../../shared/ui/modal/modal.component';
import { PagerComponent } from '../../../../shared/ui/pager/pager.component';
import { StatusBadgeComponent } from '../../../../shared/ui/status-badge/status-badge.component';
import { ToastService } from '../../../../shared/ui/toast/toast.service';
interface Room{id:string;branchId:string;roomTypeId:string;roomTypeName:string;roomNumber:string;floor:number;status:string}
interface RoomType{id:string;name:string}
@Component({selector:'app-rooms-page',standalone:true,imports:[FormsModule,LucideCirclePlus,LucideDoorOpen,LucidePencil,LucideSearch,LucideTrash2,ModalComponent,PagerComponent,StatusBadgeComponent],templateUrl:'./rooms.page.html',styleUrl:'./rooms.page.css',changeDetection:ChangeDetectionStrategy.OnPush})
export class RoomsPage implements OnInit {private readonly api=inject(ApiClientService);private readonly toast=inject(ToastService);readonly rows=signal<Room[]>([]);readonly types=signal<RoomType[]>([]);readonly page=signal(1);readonly total=signal(0);readonly search=signal('');readonly modal=signal(false);readonly editId=signal<string|null>(null);roomNumber='';roomTypeId='';floor=1;ngOnInit(){this.load();this.loadTypes()}load(){this.api.get<PagedResult<Room>|Room[]>('rooms',{pageNumber:this.page(),pageSize:20,search:this.search()}).subscribe(v=>{const p=normalizePaged(v);this.rows.set(p.items);this.total.set(p.totalItems)})}loadTypes(){this.api.get<PagedResult<RoomType>|RoomType[]>('room-types',{pageNumber:1,pageSize:100}).subscribe(v=>this.types.set(normalizePaged(v).items))}setSearch(e:Event){this.search.set((e.target as HTMLInputElement).value);this.page.set(1);this.load()}changePage(p:number){this.page.set(p);this.load()}create(){this.editId.set(null);this.roomNumber='';this.roomTypeId=this.types()[0]?.id??'';this.floor=1;this.modal.set(true)}edit(r:Room){this.editId.set(r.id);this.roomNumber=r.roomNumber;this.roomTypeId=r.roomTypeId;this.floor=r.floor;this.modal.set(true)}save(){const body={roomNumber:this.roomNumber,roomTypeId:this.roomTypeId,floor:this.floor};const id=this.editId();const req=id?this.api.put<Room>(`rooms/${id}`,body):this.api.post<Room>('rooms',body);req.subscribe(()=>{this.toast.success('Room saved');this.modal.set(false);this.load()})}status(r:Room,e:Event){const status=(e.target as HTMLSelectElement).value;this.api.patch<void>(`rooms/${r.id}/status`,{status}).subscribe(()=>{this.toast.success(`Room ${r.roomNumber} marked ${status}`);this.load()})}remove(r:Room){if(!confirm(`Delete room ${r.roomNumber}?`))return;this.api.delete<void>(`rooms/${r.id}`).subscribe(()=>{this.toast.success('Room deleted');this.load()})}}
