import { ChangeDetectionStrategy, Component, computed, inject, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { LucideCirclePlus, LucideKeyRound, LucidePencil, LucideSearch, LucideShieldCheck, LucideTrash2, LucideUserRound, LucideUserX } from '@lucide/angular';
import { AuthStore } from '../../../../core/auth/auth.store';
import { ApiClientService } from '../../../../core/http/api-client.service';
import { TranslationPipe } from '../../../../core/i18n/translation.pipe';
import { ModalComponent } from '../../../../shared/ui/modal/modal.component';
import { StatusBadgeComponent } from '../../../../shared/ui/status-badge/status-badge.component';
import { ToastService } from '../../../../shared/ui/toast/toast.service';
interface UserRow{id:string;fullName:string;email:string;isActive:boolean;hotelId?:string;branchId?:string;roles:string[]}
interface RoleRow{id:string;name:string}
@Component({selector:'app-users-page',standalone:true,imports:[FormsModule,LucideCirclePlus,LucideKeyRound,LucidePencil,LucideSearch,LucideShieldCheck,LucideTrash2,LucideUserRound,LucideUserX,ModalComponent,StatusBadgeComponent,TranslationPipe],templateUrl:'./users.page.html',styleUrl:'./users.page.css',changeDetection:ChangeDetectionStrategy.OnPush})
export class UsersPage implements OnInit {
 readonly auth=inject(AuthStore);private readonly api=inject(ApiClientService);private readonly toast=inject(ToastService);readonly users=signal<UserRow[]>([]);readonly roles=signal<RoleRow[]>([]);readonly search=signal('');readonly modal=signal(false);readonly resetModal=signal(false);readonly editId=signal<string|null>(null);readonly resetUser=signal<UserRow|null>(null);fullName='';email='';password='';isActive=true;selectedRoles:string[]=[];
 // SECURITY/UX RULE: current authenticated user is removed before rendering or actions.
 readonly visibleUsers=computed(()=>{const currentId=this.auth.user()?.id;const q=this.search().trim().toLowerCase();return this.users().filter(user=>user.id!==currentId).filter(user=>!q||`${user.fullName} ${user.email} ${user.roles.join(' ')}`.toLowerCase().includes(q))});
 ngOnInit(){this.load()} load(){this.api.get<UserRow[]>('users').subscribe(r=>this.users.set(r));this.api.get<RoleRow[]>('roles').subscribe(r=>this.roles.set(r))}setSearch(e:Event){this.search.set((e.target as HTMLInputElement).value)}create(){this.editId.set(null);this.fullName='';this.email='';this.password='';this.isActive=true;this.selectedRoles=[];this.modal.set(true)}edit(u:UserRow){if(u.id===this.auth.user()?.id)return;this.editId.set(u.id);this.fullName=u.fullName;this.email=u.email;this.password='';this.isActive=u.isActive;this.selectedRoles=[...u.roles];this.modal.set(true)}toggleRole(name:string,e:Event){const checked=(e.target as HTMLInputElement).checked;this.selectedRoles=checked?[...new Set([...this.selectedRoles,name])]:this.selectedRoles.filter(x=>x!==name)}save(){const id=this.editId();if(id===this.auth.user()?.id)return;const body=id?{fullName:this.fullName,email:this.email,branchId:null,isActive:this.isActive,roleNames:this.selectedRoles}:{fullName:this.fullName,email:this.email,password:this.password,branchId:null,roleNames:this.selectedRoles};(id?this.api.put<UserRow>(`users/${id}`,body):this.api.post<UserRow>('users',body)).subscribe(()=>{this.toast.success('User saved');this.modal.set(false);this.load()})}toggleActive(u:UserRow){if(u.id===this.auth.user()?.id)return;this.api.post<void>(`users/${u.id}/${u.isActive?'disable':'enable'}`,{}).subscribe(()=>{this.toast.success(u.isActive?'User disabled':'User enabled');this.load()})}openReset(u:UserRow){if(u.id===this.auth.user()?.id)return;this.resetUser.set(u);this.password='';this.resetModal.set(true)}resetPassword(){const u=this.resetUser();if(!u||u.id===this.auth.user()?.id)return;this.api.post<void>(`users/${u.id}/reset-password`,{password:this.password}).subscribe(()=>{this.toast.success('Password reset');this.resetModal.set(false)})}remove(u:UserRow){if(u.id===this.auth.user()?.id)return;if(!confirm(`Delete ${u.fullName}?`))return;this.api.delete<void>(`users/${u.id}`).subscribe(()=>{this.toast.success('User deleted');this.load()})}}
