import { CurrencyPipe } from '@angular/common';
import { ChangeDetectionStrategy, Component, inject, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { LucideCirclePlus, LucideGauge, LucideRefreshCw } from '@lucide/angular';
import { ApiClientService } from '../../../../core/http/api-client.service';
import { normalizePaged, PagedResult } from '../../../../shared/models/paged-result.model';
import { ModalComponent } from '../../../../shared/ui/modal/modal.component';
import { ToastService } from '../../../../shared/ui/toast/toast.service';
interface Meter{id:string;roomId:string;roomNumber:string;type:string;meterNumber:string;ratePerUnit:number;lastReading:number}
interface Reading{id:string;utilityMeterId:string;previousReading:number;currentReading:number;usage:number;ratePerUnit:number;amount:number;readingDate:string}
interface Room{id:string;roomNumber:string}
@Component({selector:'app-utilities-page',standalone:true,imports:[CurrencyPipe,FormsModule,LucideCirclePlus,LucideGauge,LucideRefreshCw,ModalComponent],templateUrl:'./utilities.page.html',styleUrl:'./utilities.page.css',changeDetection:ChangeDetectionStrategy.OnPush})
export class UtilitiesPage implements OnInit{private api=inject(ApiClientService);private toast=inject(ToastService);meters=signal<Meter[]>([]);rooms=signal<Room[]>([]);readings=signal<Reading[]>([]);selectedMeter=signal<Meter|null>(null);meterModal=signal(false);readingModal=signal(false);roomId='';type='Electricity';meterNumber='';ratePerUnit=0.25;currentReading=0;readingDate=new Date().toISOString().slice(0,10);ngOnInit(){this.load()}load(){this.api.get<Meter[]>('utility-meters').subscribe(x=>{this.meters.set(x);if(!this.selectedMeter()&&x.length)this.selectMeter(x[0])});this.api.get<PagedResult<Room>|Room[]>('rooms',{pageNumber:1,pageSize:100}).subscribe(x=>this.rooms.set(normalizePaged(x).items))}selectMeter(m:Meter){this.selectedMeter.set(m);this.api.get<Reading[]>(`meter-readings/meter/${m.id}`).subscribe(x=>this.readings.set(x))}newMeter(){this.roomId=this.rooms()[0]?.id??'';this.type='Electricity';this.meterNumber='';this.ratePerUnit=.25;this.meterModal.set(true)}saveMeter(){this.api.post<Meter>('utility-meters',{roomId:this.roomId,type:this.type,meterNumber:this.meterNumber,ratePerUnit:this.ratePerUnit}).subscribe(()=>{this.toast.success('Utility meter created');this.meterModal.set(false);this.load()})}newReading(){const m=this.selectedMeter();if(!m)return;this.currentReading=m.lastReading;this.readingDate=new Date().toISOString().slice(0,10);this.readingModal.set(true)}saveReading(){const m=this.selectedMeter();if(!m)return;this.api.post<Reading>('meter-readings',{utilityMeterId:m.id,currentReading:this.currentReading,readingDate:this.readingDate}).subscribe(()=>{this.toast.success('Meter reading recorded');this.readingModal.set(false);this.load();this.selectMeter(m)})}}
