import { ChangeDetectionStrategy, Component, inject, input, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { LucideCirclePlus, LucideRefreshCw, LucideSparkles, LucideWrench } from '@lucide/angular';
import { ApiClientService } from '../../../../core/http/api-client.service';
import { normalizePaged, PagedResult } from '../../../../shared/models/paged-result.model';
import { ModalComponent } from '../../../../shared/ui/modal/modal.component';
import { StatusBadgeComponent } from '../../../../shared/ui/status-badge/status-badge.component';
import { ToastService } from '../../../../shared/ui/toast/toast.service';
type Row=Record<string,unknown>&{id?:string;status?:string;roomId?:string;roomNumber?:string}; interface Room{id:string;roomNumber:string}
@Component({selector:'app-workboard-page',standalone:true,imports:[FormsModule,LucideCirclePlus,LucideRefreshCw,LucideSparkles,LucideWrench,ModalComponent,StatusBadgeComponent],templateUrl:'./workboard.page.html',styleUrl:'./workboard.page.css',changeDetection:ChangeDetectionStrategy.OnPush})
export class WorkboardPage implements OnInit {readonly mode=input<'housekeeping'|'maintenance'>('housekeeping');private api=inject(ApiClientService);private toast=inject(ToastService);rows=signal<Row[]>([]);rooms=signal<Room[]>([]);modal=signal(false);roomId='';taskType='Checkout Cleaning';priority='Normal';category='General';description='';ngOnInit(){this.load()}title(){return this.mode()==='housekeeping'?'Housekeeping':'Maintenance'}load(){this.api.get<Row[]>(this.mode()).subscribe(x=>this.rows.set(x));this.api.get<PagedResult<Room>|Room[]>('rooms',{pageNumber:1,pageSize:100}).subscribe(x=>this.rooms.set(normalizePaged(x).items))}create(){this.roomId=this.rooms()[0]?.id??'';this.taskType='Checkout Cleaning';this.priority='Normal';this.category='General';this.description='';this.modal.set(true)}save(){const body=this.mode()==='housekeeping'?{roomId:this.roomId,taskType:this.taskType,priority:this.priority}:{roomId:this.roomId||null,category:this.category,description:this.description,priority:this.priority};this.api.post(this.mode(),body).subscribe(()=>{this.toast.success(`${this.title()} task created`);this.modal.set(false);this.load()})}complete(row:Row){const id=String(row.id??'');if(!id)return;this.api.post(`${this.mode()}/${id}/complete`,{}).subscribe(()=>{this.toast.success('Task completed');this.load()})}text(r:Row,key:string){return String(r[key]??'—')}}
