import { ChangeDetectionStrategy, Component, inject, input, OnInit, signal } from '@angular/core';
import { LucideRefreshCw, LucideSearch } from '@lucide/angular';
import { ApiClientService } from '../../../core/http/api-client.service';
import { normalizePaged, PagedResult } from '../../models/paged-result.model';
import { PagerComponent } from '../../ui/pager/pager.component';
import { StatusBadgeComponent } from '../../ui/status-badge/status-badge.component';
export interface ExplorerColumn{key:string;label:string;type?:'text'|'money'|'date'|'status'}
type Row=Record<string,unknown>&{id?:string};
@Component({selector:'app-data-explorer-page',standalone:true,imports:[LucideRefreshCw,LucideSearch,PagerComponent,StatusBadgeComponent],templateUrl:'./data-explorer.page.html',styleUrl:'./data-explorer.page.css',changeDetection:ChangeDetectionStrategy.OnPush})
export class DataExplorerPage implements OnInit {readonly title=input.required<string>();readonly subtitle=input('Live records from the hotel management API.');readonly endpoint=input.required<string>();readonly columns=input.required<ExplorerColumn[]>();private readonly api=inject(ApiClientService);readonly rows=signal<Row[]>([]);readonly page=signal(1);readonly total=signal(0);readonly search=signal('');readonly loading=signal(false);ngOnInit(){this.load()}load(){this.loading.set(true);this.api.get<PagedResult<Row>|Row[]>(this.endpoint(),{pageNumber:this.page(),page:this.page(),pageSize:20,size:20,search:this.search()}).subscribe({next:v=>{const p=normalizePaged(v);this.rows.set(p.items);this.total.set(p.totalItems);this.loading.set(false)},error:()=>this.loading.set(false)})}setSearch(e:Event){this.search.set((e.target as HTMLInputElement).value);this.page.set(1);this.load()}changePage(p:number){this.page.set(p);this.load()}display(row:Row,col:ExplorerColumn){const value=row[col.key];if(value===null||value===undefined||value==='')return '—';if(col.type==='money')return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(value));if(col.type==='date'){const d=new Date(String(value));return Number.isNaN(d.getTime())?String(value):d.toLocaleString()}return String(value)}}
