import { CurrencyPipe } from '@angular/common';
import { ChangeDetectionStrategy, Component, inject, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { LucideCalendarCheck2, LucideCirclePlus, LucideLogIn, LucideLogOut, LucideSearch, LucideXCircle } from '@lucide/angular';
import { ApiClientService } from '../../../../core/http/api-client.service';
import { normalizePaged, PagedResult } from '../../../../shared/models/paged-result.model';
import { ModalComponent } from '../../../../shared/ui/modal/modal.component';
import { PagerComponent } from '../../../../shared/ui/pager/pager.component';
import { StatusBadgeComponent } from '../../../../shared/ui/status-badge/status-badge.component';
import { ToastService } from '../../../../shared/ui/toast/toast.service';
interface Reservation{id:string;reservationNumber:string;guestId:string;guestName:string;roomTypeId:string;roomTypeName:string;roomId?:string;roomNumber?:string;checkInDate:string;checkOutDate:string;nights:number;nightlyRate:number;totalAmount:number;status:string}
interface Option{id:string;name?:string;fullName?:string;roomNumber?:string;baseRate?:number}
@Component({selector:'app-reservations-page',standalone:true,imports:[CurrencyPipe,FormsModule,LucideCalendarCheck2,LucideCirclePlus,LucideLogIn,LucideLogOut,LucideSearch,LucideXCircle,ModalComponent,PagerComponent,StatusBadgeComponent],templateUrl:'./reservations.page.html',styleUrl:'./reservations.page.css',changeDetection:ChangeDetectionStrategy.OnPush})
export class ReservationsPage implements OnInit {
 private readonly api=inject(ApiClientService);private readonly toast=inject(ToastService);readonly rows=signal<Reservation[]>([]);readonly guests=signal<Option[]>([]);readonly roomTypes=signal<Option[]>([]);readonly rooms=signal<Option[]>([]);readonly page=signal(1);readonly total=signal(0);readonly search=signal('');readonly modal=signal(false);readonly checkin=signal<Reservation|null>(null);guestId='';roomTypeId='';roomId='';checkInDate=this.date(0);checkOutDate=this.date(1);adults=1;children=0;nightlyRate=50;checkInRoomId='';
 ngOnInit(){this.load();this.options()} load(){this.api.get<PagedResult<Reservation>|Reservation[]>('reservations',{pageNumber:this.page(),pageSize:20,search:this.search()}).subscribe(v=>{const p=normalizePaged(v);this.rows.set(p.items);this.total.set(p.totalItems)})} options(){this.api.get<PagedResult<Option>|Option[]>('guests',{pageNumber:1,pageSize:100}).subscribe(v=>this.guests.set(normalizePaged(v).items));this.api.get<PagedResult<Option>|Option[]>('room-types',{pageNumber:1,pageSize:100}).subscribe(v=>this.roomTypes.set(normalizePaged(v).items));this.api.get<PagedResult<Option>|Option[]>('rooms',{pageNumber:1,pageSize:100}).subscribe(v=>this.rooms.set(normalizePaged(v).items))}setSearch(e:Event){this.search.set((e.target as HTMLInputElement).value);this.page.set(1);this.load()}changePage(p:number){this.page.set(p);this.load()}create(){this.guestId=this.guests()[0]?.id??'';this.roomTypeId=this.roomTypes()[0]?.id??'';this.roomId='';this.checkInDate=this.date(0);this.checkOutDate=this.date(1);this.adults=1;this.children=0;this.nightlyRate=Number(this.roomTypes()[0]?.baseRate??50);this.modal.set(true)}save(){const body={guestId:this.guestId,roomTypeId:this.roomTypeId,roomId:this.roomId||null,checkInDate:this.checkInDate,checkOutDate:this.checkOutDate,adults:this.adults,children:this.children,nightlyRate:this.nightlyRate};this.api.post<Reservation>('reservations',body).subscribe(()=>{this.toast.success('Reservation created');this.modal.set(false);this.load()})}cancel(r:Reservation){if(!confirm(`Cancel ${r.reservationNumber}?`))return;this.api.post<void>(`reservations/${r.id}/cancel`,{}).subscribe(()=>{this.toast.success('Reservation cancelled');this.load()})}openCheckin(r:Reservation){this.checkin.set(r);this.checkInRoomId=r.roomId??this.rooms()[0]?.id??''}doCheckin(){const r=this.checkin();if(!r)return;this.api.post<void>(`reservations/${r.id}/check-in`,{roomId:this.checkInRoomId}).subscribe(()=>{this.toast.success('Guest checked in');this.checkin.set(null);this.load()})}checkout(r:Reservation){if(!confirm(`Check out ${r.guestName}?`))return;this.api.post<void>(`reservations/${r.id}/check-out`,{}).subscribe(()=>{this.toast.success('Guest checked out');this.load()})}private date(add:number){const d=new Date();d.setDate(d.getDate()+add);return d.toISOString().slice(0,10)}
}
