import { ChangeDetectionStrategy, Component, inject, input, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { LucideBedDouble, LucideLogIn, LucideLogOut, LucideRefreshCw } from '@lucide/angular';
import { ApiClientService } from '../../../../core/http/api-client.service';
import { normalizePaged, PagedResult } from '../../../../shared/models/paged-result.model';
import { StatusBadgeComponent } from '../../../../shared/ui/status-badge/status-badge.component';
import { ToastService } from '../../../../shared/ui/toast/toast.service';
interface Reservation{id:string;reservationNumber:string;guestName:string;roomId?:string;roomNumber?:string;roomTypeName:string;checkInDate:string;checkOutDate:string;status:string}
interface Room{id:string;roomNumber:string;status:string}
@Component({selector:'app-check-in-out-page',standalone:true,imports:[FormsModule,LucideBedDouble,LucideLogIn,LucideLogOut,LucideRefreshCw,StatusBadgeComponent],templateUrl:'./check-in-out.page.html',styleUrl:'./check-in-out.page.css',changeDetection:ChangeDetectionStrategy.OnPush})
export class CheckInOutPage implements OnInit {readonly mode=input<'check-in'|'check-out'>('check-in');private readonly api=inject(ApiClientService);private readonly toast=inject(ToastService);readonly rows=signal<Reservation[]>([]);readonly rooms=signal<Room[]>([]);readonly roomSelection=signal<Record<string,string>>({});ngOnInit(){this.load()}load(){this.api.get<PagedResult<Reservation>|Reservation[]>('reservations',{pageNumber:1,pageSize:100}).subscribe(v=>{const status=this.mode()==='check-in'?'Confirmed':'CheckedIn';this.rows.set(normalizePaged(v).items.filter(x=>x.status===status))});this.api.get<PagedResult<Room>|Room[]>('rooms',{pageNumber:1,pageSize:100}).subscribe(v=>this.rooms.set(normalizePaged(v).items.filter(x=>!['Occupied','Maintenance','OutOfOrder','Blocked'].includes(x.status))))}select(id:string,e:Event){this.roomSelection.update(x=>({...x,[id]:(e.target as HTMLSelectElement).value}))}perform(r:Reservation){if(this.mode()==='check-in'){const roomId=this.roomSelection()[r.id]||r.roomId||'';if(!roomId){this.toast.error('Select a room before check-in');return}this.api.post<void>(`reservations/${r.id}/check-in`,{roomId}).subscribe(()=>{this.toast.success(`${r.guestName} checked in`);this.load()})}else{if(!confirm(`Check out ${r.guestName}?`))return;this.api.post<void>(`reservations/${r.id}/check-out`,{}).subscribe(()=>{this.toast.success(`${r.guestName} checked out`);this.load()})}}}
